import LegalPageShell from "@/components/legal/legal-page-shell";

export default function TermsAndConditionsPage() {
    return (
        <LegalPageShell
            kicker="Legal"
            title="Terms & Conditions"
            subtitle="Please read these Terms of Use carefully before creating an account or using the platform."
        >
            <section className="legal-section">
                <p className="legal-paragraph">
                    This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>

                <p className="legal-paragraph">
                    These Terms of Use govern your usage of the website <span className="text-foreground">https://flipkartacademy.com/</span>, its mobile application, and m-site (hereinafter referred to as the “Platform”) owned and operated by Flipkart Internet Private Limited, a company incorporated under the Companies Act, 1956 with its registered office at Buildings Alyssa, Begonia &amp; Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India, and its affiliates (collectively “Flipkart, we, our, us”). Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these Terms of Use. By impliedly or expressly accepting these Terms of Use, you also accept and agree to be bound by Flipkart policies, including the Privacy Policy, as amended from time to time.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Acceptance of Terms</h2>
                <p className="legal-paragraph">
                    By creating an account on the Platform or accessing or using our Platform, you agree to enter into a legally binding contract with Flipkart, even if you are using third party credentials or using our Platform on behalf of a company. If you do not agree to these Terms of Use, do not create an account or access or otherwise use our Platform. If you wish to terminate this contract at any time, you can do so by closing your account and no longer accessing or using our Platform.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Intellectual Property</h2>
                <p className="legal-paragraph">
                    With the exception of the following, Flipkart owns all information, content, material, trademarks, service marks, trade names, and trade secrets found on the Platform, including but not limited to the software, text, images, graphics, video, script, and audio. Without prior written consent from Flipkart, no proprietary information may be copied, downloaded, reproduced, altered, republished, uploaded, posted, transmitted, or distributed in any way.
                </p>
                <p className="legal-paragraph">
                    Nothing on this Platform will be interpreted as giving the user a license or any other right, interest, or title to any of Flipkart’s intellectual property rights. You may own the medium on which the information, content or materials resides, but Flipkart shall at all times retain full and complete title to the information, content or materials and all intellectual property rights inserted by Flipkart on such medium.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Information on the Platform</h2>
                <p className="legal-paragraph">
                    The information available on the Platform is on a best effort basis and Flipkart disclaims all liability for any error and accuracy that may be available on the Platform. Flipkart reserves the right and discretion to make any changes, corrections, withdrawals, or additions to the content at any time without notice.
                </p>
                <p className="legal-paragraph">
                    Flipkart does not provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on the Platform for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
                </p>
                <p className="legal-paragraph">
                    Opinions and viewpoints may be present in some of the Platform&apos;s material. Flipkart disclaims all liability for such views and any assertions that may arise from them. Furthermore, Flipkart makes no guarantees or representations of any kind concerning the completeness, adequacy, quality, or content of such data and information.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Account Registration and Access</h2>
                <p className="legal-paragraph">
                    You must register with the Platform and keep an account with it in order to have access to the Platform and utilize its services. You will be asked to provide specific information, such as your name, cellphone number, email address, residence address, and any other facts the Platform deems essential.
                </p>
                <ol className="legal-list">
                    <li>
                        It is entirely your obligation to make sure that the account information you give is correct, comprehensive, and up to date. You will be in charge of any activity that takes place under your account and of keeping the account information private. You commit to making sure you log out of your account successfully at the conclusion of each session and promptly alerting Flipkart to any unauthorized use of your account.
                    </li>
                    <li>
                        Without imposing any obligation on Flipkart, we may ask you to change your password or suspend your account for as long as we think it is necessary if there is cause to suspect that there may be security breach or account misuse. Any loss or harm resulting from your noncompliance with this clause will not be our responsibility.
                    </li>
                    <li>
                        You understand that Flipkart cannot guarantee that the Platform will always be accessible and that your ability to utilize your account depends on outside variables such as internet service providers and network availability.
                    </li>
                    <li>
                        In addition to the disclaimers set forth in these Terms, Flipkart shall not be liable to you for any damages arising from your inability to log into your account and access the services of the Platform at any time.
                    </li>
                </ol>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Eligibility</h2>
                <p className="legal-paragraph">
                    By using the Platform, you guarantee that all the information you provide is accurate and complete. If you are under 18, you must have the consent of a parent or legal guardian. Flipkart reserves the right to cancel your account or deny access to its Platform if you are under 18 without consent or if you provide inaccurate information. You are responsible for ensuring you meet the eligibility requirements. Minors must get parental or guardian consent before sharing personal information on the Platform.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Indemnity and Liability</h2>
                <p className="legal-paragraph">
                    You agree to protect Flipkart, its employees, and agents, from any claims, damages, or losses arising from your use of the Platform, violation of terms, infringement of third-party rights, or harm caused by your use of the Platform. This clause shall survive the termination of this contract.
                </p>
                <p className="legal-paragraph">
                    Flipkart is not liable for any special, indirect, or consequential damages resulting from your use of the Platform.
                </p>
                <p className="legal-paragraph">
                    If you breach these terms, Flipkart may be irreparably harmed and seek legal remedies like injunctions. Flipkart may also disclose your account information to legal authorities in case of violations. Violating these terms could lead to civil or criminal liability.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Governing Law and Changes</h2>
                <p className="legal-paragraph">
                    These terms are governed by Indian law, and any disputes will be resolved in Bangalore courts.
                </p>
                <p className="legal-paragraph">
                    Flipkart can change, modify, suspend, or discontinue any aspect of its Platform without notice. Flipkart can also modify these terms without prior notice. Flipkart is under no obligation to maintain or continue any aspect of the Platform.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Limitation of Liability</h2>
                <p className="legal-paragraph">
                    By using the Platform, you agree that the liability of Flipkart, its parents, affiliates, related companies, officers, directors, employees, agents, representatives, partners and licensors, shall be limited to the maximum extent permissible by applicable law.
                </p>
                <p className="legal-paragraph">
                    In no case shall Flipkart, its directors, officers, employees, affiliates, agents, contractors, principals, or licensors be liable for any direct, indirect, incidental, punitive, special, or consequential damages arising from your use of the Platform or any content or for any other claim related in any way to your access to the Platform, including any errors or omissions in any content or information on the Platform, or any loss or damage of any kind incurred as a result of the use of the Platform and/or reliance on any content or information on the Platform.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Indemnification</h2>
                <p className="legal-paragraph">
                    You shall defend, indemnify and hold harmless Flipkart, its owners, affiliates, subsidiaries, group companies, partners, and their respective officers, directors, agents, and employees from and against any claim, demand, damages, obligations, penalty, losses or actions, including reasonable attorneys&apos; fees, made by any third party against them or imposed against them, due to or arising out of your or your affiliate&apos;s or relative&apos;s breach of these Terms, the Privacy Policy and/or any other policies, violation of any applicable law, rules, regulations, violation of the rights of a third party or Flipkart, or unauthorized, improper, illegal or wrongful use of your account.
                </p>
                <p className="legal-paragraph">
                    This indemnification obligation will survive the expiry or termination of these Terms and/or your use of the Platform.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Disclaimer</h2>
                <p className="legal-paragraph">
                    The Platform is provided “as is” without warranties. Flipkart disclaims all warranties, including implied warranties of merchantability and fitness for a particular purpose. Flipkart is not liable for any damages arising from using the Platform. Your use of the Platform and its content is at your own risk.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">General Provisions</h2>
                <p className="legal-paragraph">
                    Notices from Flipkart will be sent to your account email or as a general notification on the platform. Notices to Flipkart should be sent to <span className="text-foreground">scoa@flipkart.com</span>.
                </p>
                <p className="legal-paragraph">
                    These terms, along with the Privacy Policy and other applicable guidelines, constitute the entire agreement between you and Flipkart regarding your use of the platform and services.
                </p>
                <p className="legal-paragraph">
                    You cannot transfer your obligations or rights under these terms to a third party. Flipkart can transfer its rights to third parties without your consent.
                </p>
                <p className="legal-paragraph">
                    In the event that any provision of these Terms shall be deemed by any court having jurisdiction thereon to be illegal, invalid or unenforceable, it shall in no way affect or prejudice the legality, validity or enforceability of any other term or condition.
                </p>
                <p className="legal-paragraph">
                    The failure of any party to enforce any term or provision hereof shall not be construed to be a waiver of such term or provision and shall in no way affect the right of such party thereafter to enforce such term or provision or any term or provision hereof.
                </p>
                <p className="legal-paragraph">
                    Your relationship with Flipkart is on a principal to principal basis and by accepting these Terms of Use you agree that Flipkart is an independent contractor for all purposes.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Survival and Force Majeure</h2>
                <p className="legal-paragraph">
                    You acknowledge that your representations, undertakings, and warranties and the clauses relating to indemnities, limitation of liability, grant of license, and governing law shall survive the efflux of time and the termination of these Terms.
                </p>
                <p className="legal-paragraph">
                    Flipkart shall be under no liability whatsoever to you in the event of non-availability of the Platform or any portion thereof occasioned by an Act of God, war, disease, revolution, riot, civil commotion, strike, lockout, flood, fire, satellite failure, failure of any public utility, man-made disaster or any other cause whatsoever beyond the control of Flipkart.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Cookies, Links and Alerts</h2>
                <p className="legal-paragraph">
                    We send cookies to your computer, thereby uniquely identifying your browser. Cookies are used to track your preferences, help you login faster, and aggregated to determine user trends. This data is used to improve our Platform. Some of our features and services may not function properly if your cookies are disabled.
                </p>
                <p className="legal-paragraph">
                    We may present links in a format that enables us to keep track of whether these links have been followed. Clicking on links may take you to sites outside our domain. We are not responsible for the privacy practices of other websites and encourage users to read the privacy statements of each website that collects personally identifiable information.
                </p>
                <p className="legal-paragraph">
                    We may alert you by email or phone through SMS, call, or WhatsApp to inform you about new service offerings of the Company and its subsidiaries or affiliates or other information which we feel might be useful for you.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Public Forums, Security and Communications</h2>
                <p className="legal-paragraph">
                    When you use certain features on our website like discussion forums and post or share your personal information such as comments, messages, files, or photos, that information may be available to all users and may be in the public domain. All such sharing of information is done at your own risk.
                </p>
                <p className="legal-paragraph">
                    We are concerned about safeguarding the confidentiality of your information. We provide physical, electronic, and procedural safeguards to protect information we process and maintain. However, no security system can prevent all potential security breaches.
                </p>
                <p className="legal-paragraph">
                    When you send an email or other communication to us, we may retain those communications in order to process your inquiries, respond to your requests and improve our Platform.
                </p>
            </section>

            <section className="legal-section">
                <h2 className="legal-section-title">Changes to Terms</h2>
                <p className="legal-paragraph">
                    As the Company evolves, our Terms of Use will need to evolve as well to cover new situations. You are advised to review these Terms regularly for any changes, as continued use is deemed approval of all changes.
                </p>
            </section>
        </LegalPageShell>
    );
}