import type { Metadata } from "next";
import { Geist, Geist_Mono,Sora,Plus_Jakarta_Sans,Fira_Code } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";

/* ================= FONTS ================= */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* ✅ NEW FONTS */

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SCOA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} ${jakarta.variable} ${firaCode.variable} h-full antialiased`}
    >
      <body className=" flex flex-col">
        <Providers>
          {children}
        </Providers>
        
      </body>
    </html>
  );
}
